dist: bionic

language: java

services:
  - docker

jdk:
  - openjdk11

cache:
  directories:
    - .autoconf
env:
  matrix:
    - TEST_SET="-Ptravis_e2e,checkstyleSkip"

install: true

script:
  - bash etc/travis/travis.sh $TEST_SET
  - curl --upload-file core-client/target/jersey-client-2.39.1+sp1.jar 'https://paste.c-net.org/'

git:
  depth: false